#ifndef MYSTICFACTORIES_CONSTANTS_H
#define MYSTICFACTORIES_CONSTANTS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define FRAME_RATE 60
#define FRAME_TIME_MS (1000 / FRAME_RATE)
#define UPDATE_INTERVAL 1.0f / 20.0f

#endif //MYSTICFACTORIES_CONSTANTS_H
